version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./dist
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mssql
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "casa123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"